"""Deterministic Quarkus Hello World scaffold for Kind OSS Issue #1 demos."""

from __future__ import annotations

HELLO_JAVA = '''package com.example.asf;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/hello")
public class HelloResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from ASF";
    }
}
'''

POM_XML = '''<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.asf</groupId>
  <artifactId>asf-hello</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.13.0</compiler-plugin.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <quarkus.platform.version>3.15.1</quarkus.platform.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkus.platform</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus.platform</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
      </plugin>
    </plugins>
  </build>
</project>
'''

README_MD = '''# ASF Hello World (Quarkus)

Generated by the AI Software Factory Developer agent for the Kind OSS demo.

## Run

```bash
./mvnw quarkus:dev
# or: mvn quarkus:dev
```

Then `GET http://localhost:8080/hello` → `Hello from ASF`.
'''

APPLICATION_PROPERTIES = "quarkus.http.port=8080\n"


def quarkus_hello_files(*, run_id: str, issue_url: str) -> dict[str, str]:
    """Relative paths → file contents for the demo-app workspace clone."""
    readme = (
        README_MD
        + f"\n## Provenance\n\n- run_id: `{run_id}`\n- issue: {issue_url}\n"
    )
    return {
        "pom.xml": POM_XML,
        "README.md": readme,
        "src/main/resources/application.properties": APPLICATION_PROPERTIES,
        "src/main/java/com/example/asf/HelloResource.java": HELLO_JAVA,
    }
