#!/usr/bin/env bash
# Workshop bootstrap — collect/validate session params before any cluster mutate.
# Spec: workshop-bootstrap (Engram sdd/ai-software-factory/spec). ADR-011.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SESSION_DIR="${ROOT_DIR}/.workshop"
SESSION_ENV="${SESSION_DIR}/session.env"
FLAG_DRY_RUN=false
ENV_FILE="${ROOT_DIR}/.env"

usage() {
  cat <<'EOF'
Usage: scripts/workshop-bootstrap.sh [--dry-run] [--env-file PATH]

Validates MUST workshop parameters (OCP, OSAI, GitHub, GHCR, PROFILE) before
any cluster or secret mutate. With --dry-run, prints the plan and exits without
writing session files or applying cluster resources.

See docs/workshop/bootstrap.md and .env.example.
EOF
}

log() { printf '%s\n' "$*"; }
err() { printf 'ERROR: %s\n' "$*" >&2; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) FLAG_DRY_RUN=true; shift ;;
    --env-file)
      ENV_FILE="${2:-}"
      if [[ -z "${ENV_FILE}" ]]; then err "--env-file requires a path"; exit 2; fi
      shift 2
      ;;
    -h|--help) usage; exit 0 ;;
    *) err "unknown argument: $1"; usage; exit 2 ;;
  esac
done

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

ENV_DRY_RUN="${DRY_RUN:-false}"
DRY_RUN=false
case "${ENV_DRY_RUN}" in
  1|true|TRUE|yes|YES) DRY_RUN=true ;;
esac
if [[ "${FLAG_DRY_RUN}" == "true" ]]; then
  DRY_RUN=true
fi

MISSING=()
INVALID=()

require_nonempty() {
  local name="$1"
  local value="${!name-}"
  if [[ -z "${value}" ]]; then
    MISSING+=("${name}")
  fi
}

require_profile() {
  local value="${PROFILE:-}"
  case "${value}" in
    minimal|standard|full) ;;
    "")
      MISSING+=("PROFILE")
      ;;
    *)
      INVALID+=("PROFILE must be minimal|standard|full (got: ${value})")
      ;;
  esac
}

require_nonempty OCP_API_URL
if [[ -z "${OCP_TOKEN:-}" && -z "${KUBECONFIG:-}" ]]; then
  MISSING+=("OCP_TOKEN or KUBECONFIG")
fi
require_nonempty OSAI_INFERENCE_URL
require_nonempty OSAI_MODEL_ID
require_nonempty GITHUB_TOKEN
require_nonempty GITHUB_OWNER
require_nonempty GITHUB_REPO
require_nonempty GHCR_TOKEN
require_profile

: "${NAMESPACE_PREFIX:=asf-workshop-}"
: "${CHECKPOINT_DSN:=}"
: "${INFERENCE_GATEWAY_URL:=http://127.0.0.1:8081}"
: "${ORCHESTRATOR_URL:=http://127.0.0.1:8080}"

if [[ ${#MISSING[@]} -gt 0 || ${#INVALID[@]} -gt 0 ]]; then
  err "bootstrap schema validation failed — refusing cluster mutate"
  if [[ ${#MISSING[@]} -gt 0 ]]; then
    err "missing MUST fields:"
    for f in "${MISSING[@]}"; do err "  - ${f}"; done
  fi
  if [[ ${#INVALID[@]} -gt 0 ]]; then
    err "invalid fields:"
    for f in "${INVALID[@]}"; do err "  - ${f}"; done
  fi
  err "copy .env.example → .env and fill values, or export vars. See docs/workshop/bootstrap.md"
  exit 1
fi

log "bootstrap validation OK"
log "  PROFILE=${PROFILE}"
log "  OCP_API_URL=${OCP_API_URL}"
log "  OSAI_INFERENCE_URL=${OSAI_INFERENCE_URL}"
log "  OSAI_MODEL_ID=${OSAI_MODEL_ID}"
log "  GITHUB_OWNER/REPO=${GITHUB_OWNER}/${GITHUB_REPO}"
log "  NAMESPACE_PREFIX=${NAMESPACE_PREFIX}"
log "  CHECKPOINT_DSN=${CHECKPOINT_DSN:-<unset — orchestrator may use memory checkpointer in local boot>}"
log "  DRY_RUN=${DRY_RUN}"

if [[ "${DRY_RUN}" == "true" ]]; then
  log "dry-run: skipping session writes and cluster mutate"
  log "bootstrap.completed (dry-run)"
  exit 0
fi

mkdir -p "${SESSION_DIR}"
umask 077
cat >"${SESSION_ENV}" <<EOF
# Generated by workshop-bootstrap.sh — do not commit
OCP_API_URL=${OCP_API_URL}
OCP_TOKEN=${OCP_TOKEN:-}
KUBECONFIG=${KUBECONFIG:-}
OSAI_INFERENCE_URL=${OSAI_INFERENCE_URL}
OSAI_MODEL_ID=${OSAI_MODEL_ID}
OSAI_API_KEY=${OSAI_API_KEY:-}
GITHUB_TOKEN=${GITHUB_TOKEN}
GITHUB_OWNER=${GITHUB_OWNER}
GITHUB_REPO=${GITHUB_REPO}
GHCR_TOKEN=${GHCR_TOKEN}
RHDH_URL=${RHDH_URL:-}
RHDH_TOKEN=${RHDH_TOKEN:-}
GITOPS_REPO_URL=${GITOPS_REPO_URL:-}
NAMESPACE_PREFIX=${NAMESPACE_PREFIX}
PROFILE=${PROFILE}
CHECKPOINT_DSN=${CHECKPOINT_DSN:-}
INFERENCE_GATEWAY_URL=${INFERENCE_GATEWAY_URL}
ORCHESTRATOR_URL=${ORCHESTRATOR_URL}
INFERENCE_FALLBACK=${INFERENCE_FALLBACK:-false}
DRY_RUN=false
EOF
chmod 600 "${SESSION_ENV}"

log "wrote session env: ${SESSION_ENV}"
log "NOTE: K8s Secret apply is deferred to platform apply scripts (M2+); schema gate passed."
log "bootstrap.completed"
exit 0
