#!/usr/bin/env bash
# Generate Kind OSS Deployments/Services for factory workloads (one shared image).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
OUT="${ROOT}/platform/kind/apps/factory-workloads.yaml"
IMAGE="${ASF_FACTORY_IMAGE:-localhost/asf-factory:kind}"

# name|uvicorn_app|port|extra_env_lines (optional, use ;; as newline stand-in — keep simple: no extras in generator)
SERVICES=(
  "asf-inference-gateway|inference_gateway.app:app|8081|GATEWAY_STUB_MODE"
  "asf-orchestrator|orchestrator.app:app|8080|"
  "asf-status|asf_status:app|8090|"
  "asf-agent-pm|agent_pm.app:app|8080|"
  "asf-agent-architect|agent_architect.app:app|8080|"
  "asf-agent-developer|agent_developer.app:app|8080|"
  "asf-agent-reviewer|agent_reviewer.app:app|8080|"
  "asf-agent-security|agent_security.app:app|8080|"
  "asf-agent-qa|agent_qa.app:app|8080|"
  "asf-agent-documentation|agent_documentation.app:app|8080|"
  "asf-agent-deployment|agent_deployment.app:app|8080|"
  "asf-agent-sre|agent_sre.app:app|8080|"
  "asf-mcp-github|mcp_github.server:app|8091|"
  "asf-mcp-filesystem|mcp_filesystem.server:app|8092|"
  "asf-mcp-git|mcp_git.server:app|8093|"
  "asf-mcp-kubernetes|mcp_kubernetes.server:app|8095|"
)

{
  cat <<'HDR'
# Generated by platform/kind/apps/generate-workloads.sh — do not hand-edit permanently.
# Recreate: ./platform/kind/apps/generate-workloads.sh
---
apiVersion: v1
kind: Namespace
metadata:
  name: asf-factory
  labels:
    app.kubernetes.io/part-of: ai-software-factory
    asf.profile: kind-oss
---
apiVersion: v1
kind: Secret
metadata:
  name: asf-workshop-secrets
  namespace: asf-factory
type: Opaque
stringData:
  OSAI_MODEL_ID: "stub-small-model"
  GITHUB_TOKEN: "kind-local-unused"
  GITHUB_OWNER: "fmenesesg"
  GITHUB_REPO: "ai-software-factory"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: asf-kind-config
  namespace: asf-factory
data:
  INFERENCE_GATEWAY_URL: "http://asf-inference-gateway:8081"
  OSAI_INFERENCE_URL: "http://asf-inference-gateway:8081/v1"
  GATEWAY_STUB_MODE: "true"
  AGENT_SKIP_INFERENCE: "false"
  DRY_RUN: "true"
  NAMESPACE_PREFIX: "asf-workshop-"
  MCP_GITHUB_URL: "http://asf-mcp-github:8091"
  MCP_FILESYSTEM_URL: "http://asf-mcp-filesystem:8092"
  MCP_GIT_URL: "http://asf-mcp-git:8093"
  MCP_KUBERNETES_URL: "http://asf-mcp-kubernetes:8095"
  WORKSPACE_ROOT: "/tmp/asf-workspace"
HDR

  for row in "${SERVICES[@]}"; do
    IFS='|' read -r name app port flag <<<"${row}"
    stub_env=""
    if [[ "${flag}" == "GATEWAY_STUB_MODE" ]]; then
      stub_env=$(cat <<'E'
            - name: GATEWAY_STUB_MODE
              valueFrom:
                configMapKeyRef:
                  name: asf-kind-config
                  key: GATEWAY_STUB_MODE
            - name: OSAI_INFERENCE_URL
              valueFrom:
                configMapKeyRef:
                  name: asf-kind-config
                  key: OSAI_INFERENCE_URL
E
)
    fi
    cat <<EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: asf-factory
  labels:
    app.kubernetes.io/name: ${name}
    app.kubernetes.io/part-of: ai-software-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${name}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${name}
    spec:
      containers:
        - name: app
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${port}
              name: http
          env:
            - name: ASF_UVICORN_APP
              value: "${app}"
            - name: ASF_PORT
              value: "${port}"
            - name: INFERENCE_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: asf-kind-config
                  key: INFERENCE_GATEWAY_URL
            - name: DRY_RUN
              valueFrom:
                configMapKeyRef:
                  name: asf-kind-config
                  key: DRY_RUN
            - name: NAMESPACE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: asf-kind-config
                  key: NAMESPACE_PREFIX
            - name: AGENT_SKIP_INFERENCE
              valueFrom:
                configMapKeyRef:
                  name: asf-kind-config
                  key: AGENT_SKIP_INFERENCE
            - name: OSAI_MODEL_ID
              valueFrom:
                secretKeyRef:
                  name: asf-workshop-secrets
                  key: OSAI_MODEL_ID
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: asf-workshop-secrets
                  key: GITHUB_TOKEN
            - name: GITHUB_OWNER
              valueFrom:
                secretKeyRef:
                  name: asf-workshop-secrets
                  key: GITHUB_OWNER
            - name: GITHUB_REPO
              valueFrom:
                secretKeyRef:
                  name: asf-workshop-secrets
                  key: GITHUB_REPO
${stub_env}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: asf-factory
spec:
  selector:
    app.kubernetes.io/name: ${name}
  ports:
    - name: http
      port: ${port}
      targetPort: http
EOF
  done

  cat <<'ROUTE'
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: asf-status
  namespace: asf-factory
spec:
  parentRefs:
    - name: asf
      namespace: gateway-system
  hostnames:
    - asf.demo.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /status
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: asf-status
          port: 8090
    - matches:
        - path:
            type: PathPrefix
            value: /v1
      backendRefs:
        - name: asf-inference-gateway
          port: 8081
    - matches:
        - path:
            type: PathPrefix
            value: /orch
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: asf-orchestrator
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sample-app
          port: 8080
ROUTE
} >"${OUT}"

printf 'wrote %s\n' "${OUT}"
